# Generated by Django 3.1.7 on 2021-05-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('iname', models.CharField(max_length=20)),
                ('idesc', models.CharField(max_length=100)),
                ('iprice', models.IntegerField(default=1)),
                ('ipic', models.ImageField(blank=True, default=' ', upload_to='cart')),
                ('slug', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=20)),
                ('idesc', models.CharField(max_length=100)),
                ('iprice', models.IntegerField(default=1)),
                ('ipic', models.ImageField(blank=True, default=' ', upload_to='men_images')),
                ('slug', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('iurl', models.URLField(default=' ')),
                ('iname', models.CharField(max_length=100)),
                ('ipic', models.ImageField(default=' ', upload_to='orders')),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('a1', models.CharField(default='', max_length=200)),
                ('a2', models.CharField(default='', max_length=200)),
                ('cod', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('ord_id', models.IntegerField()),
                ('update_desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='Women',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iname', models.CharField(max_length=20)),
                ('idesc', models.CharField(max_length=100)),
                ('iprice', models.IntegerField(default=1)),
                ('ipics', models.ImageField(blank=True, default=' ', upload_to='women_images')),
                ('slug', models.CharField(default=' ', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='media_files'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
