# Generated by Django 3.1.7 on 2021-05-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210529_0027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
