# Generated by Django 3.1.7 on 2021-05-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('iurl', models.URLField(default=' ')),
                ('iname', models.CharField(max_length=100)),
                ('ipic', models.ImageField(default=' ', upload_to='orders')),
                ('email', models.EmailField(default=' ', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
                ('a1', models.CharField(default='', max_length=200)),
                ('a2', models.CharField(default='', max_length=200)),
                ('cod', models.BooleanField(default='False')),
            ],
        ),
    ]
