# Generated by Django 3.1.7 on 2021-05-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='slug',
        ),
    ]
