# Generated by Django 3.1.7 on 2021-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_order_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='returns',
            fields=[
                ('return_id', models.AutoField(primary_key=True, serialize=False)),
                ('reasons', models.CharField(choices=[('not good', 'not good'), ('other product', 'not product')], max_length=100)),
            ],
        ),
    ]
